services:
  nodeapp:
    build: .
    container_name: app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo:27017/
      SECRET_KEY: docIntTacchini2024
      APP_URL: documentos.tacchini.com.br
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - docInst

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - docInst
    volumes:
      - ./data/db:/data/db
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - docInst
    volumes: 
      - ./data/cache:/data/cache

networks:
  docInst:
    driver: bridge